app:
  port: ${APP_PORT:8080}
  logging: debug
  server: 10.147.20.25:3306
  database: haberes.aud
  user: root
  password: root

server:
  port: ${app.port}

spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.database}?useSSL=false&serverTimezone=UTC
    username: ${app.user}
    password: ${app.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    web: ${app.logging}
    org:
      hibernate:
        SQL: ${app.logging}
