app:
  server: 10.147.20.25:3306
  database: haberes.aud
  user: root
  password: root
  add-properties: true
  logging: debug
  livereload:
    enabled: true
    port: 35896
  open-in-view: true

spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.database}?useSSL=false&serverTimezone=UTC
    username: ${app.user}
    password: ${app.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: ${app.open-in-view}
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: ${app.livereload.enabled}
      port: ${app.livereload.port}
    add-properties: ${app.add-properties}

logging:
  level:
    web: ${app.logging}
    org:
      hibernate:
        SQL: ${app.logging}
